site_name: 密西根学院生存指南
site_url: https://surviveumji.github.io/SurviveUMJIManual/
repo_url: https://github.com/SurviveUMJI/SurviveUMJIManual/
edit_uri: 'edit/master/docs'
use_directory_urls: false
plugins:
  - search:
      lang:
        - en
        - ja
theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
extra:
  disqus: surviveumjimanual
