site_name: 密西根学院生存指南
site_url: https://surviveumji.github.io/SurviveUMJIManual/
repo_url: https://github.com/SurviveUMJI/SurviveUMJIManual/
edit_uri: 'edit/master/docs'
use_directory_urls: false
plugins:
  - search:
      lang:
        - en
        - ja
theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  custom_dir: overrides
extra:
  disqus: surviveumjimanual
extra_javascript:
    - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
nav:
  - index.md
  - 本科生课程:
    - 本科生课程/课程给分.md
    - 本科生课程/精品课程/精品课程.md
  - 本科生助教体系:
    - 作为一名助教:
      - 我们为什么会当助教:
        - makersmelx: 本科生助教体系/作为一名助教/我们为什么会当助教/makersmelx.md
      - 本科生助教体系/作为一名助教/认清自己的价值.md
      - 本科生助教体系/作为一名助教/助教是什么.md
    - 作为一名学生:
      - 本科生助教体系/作为一名学生/助教是什么.md
  - 关于:
    - 关于/更新说明.md
    - 关于/许可协议.md
