site_name: Survive UMJI Manual
site_url: https://surviveumji.github.io/SurviveUMJIManual/
use_directory_urls: false
plugins:
  - search:
      lang:
        - en
        - ja
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
